'use strict';

var sound = require('./sound-ios');

var padsList = {
    'Ab_Major':       sound.create( '~/tracks/Ab Major.mp3' ),
    'Ab_Major_Drive': sound.create( '~/tracks/Ab Major Drive.mp3' ),
    'Ab_Minor':       sound.create( '~/tracks/Ab Minor.mp3' ),
    'Ab_Minor_Drive': sound.create( '~/tracks/Ab Minor Drive.mp3' ),
    'A_Major':        sound.create( '~/tracks/A Major.mp3' ),
    'A_Major_Drive':  sound.create( '~/tracks/A Major Drive.mp3' ),
    'A_Minor':        sound.create( '~/tracks/A Minor.mp3' ),
    'A_Minor_Drive':  sound.create( '~/tracks/A Minor Drive.mp3' ),
    'Bb_Major':       sound.create( '~/tracks/Bb Major.mp3' ),
    'Bb_Major_Drive': sound.create( '~/tracks/Bb Major Drive.mp3' ),
    'Bb_Minor':       sound.create( '~/tracks/Bb Minor.mp3' ),
    'Bb_Minor_Drive': sound.create( '~/tracks/Bb Minor Drive.mp3' ),
    'B_Major':        sound.create( '~/tracks/B Major.mp3' ),
    'B_Major_Drive':  sound.create( '~/tracks/B Major Drive.mp3' ),
    'B_Minor':        sound.create( '~/tracks/B Minor.mp3' ),
    'B_Minor_Drive':  sound.create( '~/tracks/B Minor Drive.mp3' ),
    'C_Major':        sound.create( '~/tracks/C Major.mp3' ),
    'C_Major_Drive':  sound.create( '~/tracks/C Major Drive.mp3' ),
    'C_Minor':        sound.create( '~/tracks/C Minor.mp3' ),
    'C_Minor_Drive':  sound.create( '~/tracks/C Minor Drive.mp3' ),
    'Db_Major':       sound.create( '~/tracks/Db Major.mp3' ),
    'Db_Major_Drive': sound.create( '~/tracks/Db Major Drive.mp3' ),
    'Db_Minor':       sound.create( '~/tracks/Db Minor.mp3' ),
    'Db_Minor_Drive': sound.create( '~/tracks/Db Minor Drive.mp3' ),
    'D_Major':        sound.create( '~/tracks/D Major.mp3' ),
    'D_Major_Drive':  sound.create( '~/tracks/D Major Drive.mp3' ),
    'D_Minor':        sound.create( '~/tracks/D Minor.mp3' ),
    'D_Minor_Drive':  sound.create( '~/tracks/D Minor Drive.mp3' ),
    'Eb_Major':       sound.create( '~/tracks/Eb Major.mp3' ),
    'Eb_Major_Drive': sound.create( '~/tracks/Eb Major Drive.mp3' ),
    'Eb_Minor':       sound.create( '~/tracks/Eb Minor.mp3' ),
    'Eb_Minor_Drive': sound.create( '~/tracks/Eb Minor Drive.mp3' ),
    'E_Major':        sound.create( '~/tracks/E Major.mp3' ),
    'E_Major_Drive':  sound.create( '~/tracks/E Major Drive.mp3' ),
    'E_Minor':        sound.create( '~/tracks/E Minor.mp3' ),
    'E_Minor_Drive':  sound.create( '~/tracks/E Minor Drive.mp3' ),
    'F_Major':        sound.create( '~/tracks/F Major.mp3' ),
    'F_Major_Drive':  sound.create( '~/tracks/F Major Drive.mp3' ),
    'F_Minor':        sound.create( '~/tracks/F Minor.mp3' ),
    'F_Minor_Drive':  sound.create( '~/tracks/F Minor Drive.mp3' ),
    'Gb_Major':       sound.create( '~/tracks/Gb Major.mp3' ),
    'Gb_Major_Drive': sound.create( '~/tracks/Gb Major Drive.mp3' ),
    'Gb_Minor':       sound.create( '~/tracks/Gb Minor.mp3' ),
    'Gb_Minor_Drive': sound.create( '~/tracks/Gb Minor Drive.mp3' ),
    'G_Major':        sound.create( '~/tracks/G Major.mp3' ),
    'G_Major_Drive':  sound.create( '~/tracks/G Major Drive.mp3' ),
    'G_Minor':        sound.create( '~/tracks/G Minor.mp3' ),
    'G_Minor_Drive':  sound.create( '~/tracks/G Minor Drive.mp3 ')
};

exports.padsList = padsList;
